{
 "title": "Liberando Productos Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(server_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} total requests"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(healthcheck_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls healthcheck"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(main_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls healthcheck"
    }
   ]
  },
  {
   "title": "Number of calls to bye endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(bye_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls healthcheck"
    }
   ]
  },
  {
   "title": "App total starts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(increase((kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}[$__rate_interval])))",
     "legendFormat": "{{pod}} calls create students"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"pdftron-webviewer\", cluster=\"$cluster\", container!=\"\"}[$__rate_interval])",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  }
 ]
}